version: '3'

services:
  app:
    build: .
    ports:
      - "8083:8080"
    depends_on:
      - postgres-notifications

  postgres-notifications:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    external:
      name: my-network
